PaymentDecorator:
    type: interface
    decorator: true
    config:
        description: "Represents a payment"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Payment name"
            description:
                type: "String"
                description: "Localized payment description (domain dependent)"
            instructions:
                type: "String"
                description: "Localized payment instruction (domain dependent)"
            position:
                type: "Int!"
                description: "Payment position"
            price:
                type: "Price!"
                description: "Payment price"
                resolve: '@=query("priceByPaymentQuery", value, args["cartUuid"], context)'
                args:
                    cartUuid:
                        type: "Uuid"
                        defaultValue: null
            images:
                type: "[Image!]!"
                description: "Payment images"
                resolve: '@=query("imagesByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            mainImage:
                type: "Image"
                description: "Payment image by params"
                resolve: '@=query("mainImageByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            transports:
                type: "[Transport!]!"
                description: "List of assigned transports"
                resolve: '@=query("transportsOfPaymentQuery", value, args["displayInCartOnly"])'
                args:
                    displayInCartOnly:
                        type: "Boolean"
                        defaultValue: true
            goPayPaymentMethod:
                type: "GoPayPaymentMethod"
                description: "Additional data for GoPay payment"
            type:
                type: "PaymentTypeEnum!"
                description: "Type of payment"
            vat:
                type: "Vat!"
            displayInCart:
                type: "Boolean!"
                description: "Should be displayed in cart (is used for payments, that might be needed to return for example to the Convertim, but are not supposed to be displayed in cart)"
