Product:
    type: interface
    inherits:
        - 'ProductDecorator'
    config:
        fields:
            slug:
                type: "String!"
                description: "Product URL slug"
            id:
                type: "Int!"
                description: "Product id"
            catalogNumber:
                type: "String!"
                description: "Product catalog number"
            partNumber:
                type: "String"
                description: "Product part number"
            ean:
                type: "String"
                description: "EAN"
            name:
                type: "String!"
                description: "Localized product name (domain dependent)"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
            relatedProducts:
                type: "[Product!]!"
                description: "List of related products"
            availability:
                type: "Availability!"
            images:
                type: "[Image!]!"
                description: "Product images"
                resolve: '@=query("imagesByProductPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            accessories:
                type: "[Product!]!"
            parameters:
                type: "[Parameter!]!"
            mainImage:
                type: "Image"
                description: "Product image by params"
                resolve: '@=query("mainImageByProductPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            isMainVariant:
                type: "Boolean!"
            productVideos:
                type: "[VideoToken!]!"
