overblog_graphql_endpoint:
    path: /{query}
    requirements:
        query: "^(?!batch|graphiql).*"
    defaults:
        _controller: Shopsys\FrontendApiBundle\Controller\FrontendApiController::endpointAction
        _format: 'json'
        query: ''
    stateless: true

overblog_graphql_batch_endpoint:
    path: /batch/
    defaults:
        _controller: Shopsys\FrontendApiBundle\Controller\FrontendApiController::batchEndpointAction
        _format: 'json'
