CreateWatchdogInputDecorator:
    type: input-object
    decorator: true
    config:
        fields:
            productUuid:
                type: "Uuid!"
                description: "Product UUID"
                validation:
                    -   Shopsys\FrontendApiBundle\Component\Constraints\Watchdog: ~
            email:
                type: "String!"
                description: "The customer's email address"
                validation:
                    -   NotBlank:
                            message: "Please enter email"
                    -   Email:
                            message: "Please enter valid email"
                    -   Length:
                            max: 255
                            maxMessage: "Email cannot be longer than {{ limit }} characters"
