sonata_admin:
    title: 'Shopsys Platform admin'
    title_logo: public/admin/images/logo.svg
    show_mosaic_button: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                domain: '@ShopsysAdmin/templates/domain.html.twig'
