sonata_admin:
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    default_controller: Shopsys\Administration\Controller\CRUDController
    options:
        default_group: Orders
    show_mosaic_button: false
    title: 'Shopsys Platform admin'
    title_logo: public/admin/images/logo.svg
    templates:
        layout: '@ShopsysAdministration/standard_layout.html.twig'
        form_theme:
            - '@ShopsysFramework/Admin/Form/theme.html.twig'
            - '@ShopsysFramework/Admin/Form/imageuploadFields.html.twig'
            - 'Admin/Form/grapesJsType.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
    http_cache: false

sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                domain: '@ShopsysAdministration/domain.html.twig'

sonata_form:
    form_type: standard
